compute_program: "/assets/compute/explosion.cp"
constants {
  name: "color"
  type: CONSTANT_TYPE_USER
  value {
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
  }
}
constants {
  name: "params"
  type: CONSTANT_TYPE_USER
  value {
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
  }
}
samplers {
  name: "texture_in"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_NEAREST
  filter_mag: FILTER_MODE_MAG_NEAREST
  max_anisotropy: 0.0
}
